name: Deploy Application

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Run Deployment Script
        shell: cmd
        working-directory: D:\KM-finny\KM-FINNY-Github\KM_FINNY_MERGE
        run: deploy.bat