name: Deploy Application

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Run Deployment Script
        shell: cmd
        working-directory: D:\KM-finny\TEST_FINNY\KM_FINNY_MERGE
        run: deploy.bat
